<?php

namespace BUBundle\Repository;

/**
 * HORAIRE_SALLERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HORAIRE_SALLERepository extends \Doctrine\ORM\EntityRepository
{
}
