<?php

namespace BUBundle\Repository;

/**
 * HORAIRE_EXCEPTIONNELLERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HORAIRE_EXCEPTIONNELLERepository extends \Doctrine\ORM\EntityRepository
{
}
