<?php

namespace BUBundle\Repository;

/**
 * HORAIRERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HORAIRERepository extends \Doctrine\ORM\EntityRepository
{
}
