<?php

namespace BUBundle\Repository;

/**
 * MESSAGE_POPUPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MESSAGE_POPUPRepository extends \Doctrine\ORM\EntityRepository
{
}
