<?php

namespace BUBundle\Repository;

/**
 * PHOTORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PHOTORepository extends \Doctrine\ORM\EntityRepository
{
}
