<?php

namespace BUBundle\Repository;

/**
 * RAPPORT_PLANIFIERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RAPPORT_PLANIFIERepository extends \Doctrine\ORM\EntityRepository
{
}
