<?php

namespace BUBundle\Repository;

/**
 * RESERVATIONRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RESERVATIONRepository extends \Doctrine\ORM\EntityRepository
{
}
