<?php

namespace BUBundle\Repository;

/**
 * RESPONSABLERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RESPONSABLERepository extends \Doctrine\ORM\EntityRepository
{
}
