<?php

namespace BUBundle\Repository;

/**
 * ROLERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ROLERepository extends \Doctrine\ORM\EntityRepository
{
}
