<?php

namespace BUBundle\Repository;

/**
 * SALLERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SALLERepository extends \Doctrine\ORM\EntityRepository
{
}
