<?php

namespace BUBundle\Repository;

/**
 * SERVICERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SERVICERepository extends \Doctrine\ORM\EntityRepository
{
}
