<?php

namespace BUBundle\Repository;

/**
 * UTILISATEURRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UTILISATEURRepository extends \Doctrine\ORM\EntityRepository
{
}
